import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar/NavBar";
import Footer from "./components/Footer";
import AuthProvider from "../app/utils/context"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ONECLICK HEALTH",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        <NavBar />
        {children}
        <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
